language: python

python:
  - "3.4"
  - "2.7"
  - "pypy"

before_install:
  - pip install cookiecutter
  - cookiecutter . --no-input

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r ./project_name/tests/requirements.txt
script: cd project_name && py.test

